# Generated by Django 5.2.5 on 2025-08-23 21:19

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='categorias/')),
                ('slug', models.SlugField(help_text='URL amigable', unique=True)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Ingrediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('categoria_ingrediente', models.CharField(choices=[('proteina', 'Proteína'), ('verdura', 'Verdura'), ('fruta', 'Fruta'), ('cereal', 'Cereal'), ('lacteo', 'Lácteo'), ('condimento', 'Condimento'), ('otro', 'Otro')], default='otro', max_length=50)),
            ],
            options={
                'verbose_name': 'Ingrediente',
                'verbose_name_plural': 'Ingredientes',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(help_text='Nombre de la receta', max_length=200)),
                ('descripcion', models.TextField(help_text='Descripción breve de la receta', max_length=1000)),
                ('tiempo_preparacion', models.PositiveIntegerField(help_text='Tiempo de preparación en minutos', validators=[django.core.validators.MinValueValidator(1)])),
                ('tiempo_coccion', models.PositiveIntegerField(default=0, help_text='Tiempo de cocción en minutos', validators=[django.core.validators.MinValueValidator(0)])),
                ('dificultad', models.CharField(choices=[('muy_facil', 'Muy Fácil'), ('facil', 'Fácil'), ('intermedio', 'Intermedio'), ('dificil', 'Difícil'), ('muy_dificil', 'Muy Difícil')], default='facil', max_length=15)),
                ('porciones', models.PositiveIntegerField(default=4, help_text='Número de porciones que rinde la receta', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)])),
                ('instrucciones', models.TextField(help_text='Pasos detallados para preparar la receta')),
                ('calorias_por_porcion', models.PositiveIntegerField(blank=True, help_text='Calorías aproximadas por porción', null=True)),
                ('imagen_principal', models.ImageField(blank=True, help_text='Imagen principal de la receta', null=True, upload_to='recetas/principales/')),
                ('publicada', models.BooleanField(default=False, help_text='¿La receta está publicada públicamente?')),
                ('destacada', models.BooleanField(default=False, help_text='¿Es una receta destacada?')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('vistas', models.PositiveIntegerField(default=0)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recetas', to=settings.AUTH_USER_MODEL)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recetas', to='recetas.categoria')),
            ],
            options={
                'verbose_name': 'Receta',
                'verbose_name_plural': 'Recetas',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntuacion', models.PositiveIntegerField(help_text='Puntuación de 1 a 5 estrellas', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comentario', models.TextField(blank=True, help_text='Comentario opcional sobre la receta', max_length=500)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings_dados', to=settings.AUTH_USER_MODEL)),
                ('receta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='recetas.receta')),
            ],
            options={
                'verbose_name': 'Valoración',
                'verbose_name_plural': 'Valoraciones',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='ImagenReceta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(help_text='Imagen adicional de la receta', upload_to='recetas/galeria/')),
                ('descripcion', models.CharField(blank=True, help_text='Descripción de la imagen', max_length=200)),
                ('orden', models.PositiveIntegerField(default=0, help_text='Orden de visualización')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('receta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes_adicionales', to='recetas.receta')),
            ],
            options={
                'verbose_name': 'Imagen de Receta',
                'verbose_name_plural': 'Imágenes de Recetas',
                'ordering': ['orden', 'fecha_subida'],
            },
        ),
        migrations.CreateModel(
            name='Favorito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_agregado', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoritos', to=settings.AUTH_USER_MODEL)),
                ('receta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoritos', to='recetas.receta')),
            ],
            options={
                'verbose_name': 'Favorito',
                'verbose_name_plural': 'Favoritos',
                'ordering': ['-fecha_agregado'],
            },
        ),
        migrations.CreateModel(
            name='RecetaIngrediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.CharField(help_text='Ej: 2 tazas, 500g, al gusto', max_length=100)),
                ('opcional', models.BooleanField(default=False, help_text='¿Es un ingrediente opcional?')),
                ('ingrediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recetas_uso', to='recetas.ingrediente')),
                ('receta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredientes_detalle', to='recetas.receta')),
            ],
            options={
                'verbose_name': 'Ingrediente de Receta',
                'verbose_name_plural': 'Ingredientes de Recetas',
            },
        ),
        migrations.AddIndex(
            model_name='receta',
            index=models.Index(fields=['publicada', '-fecha_creacion'], name='recetas_rec_publica_e53520_idx'),
        ),
        migrations.AddIndex(
            model_name='receta',
            index=models.Index(fields=['categoria', 'publicada'], name='recetas_rec_categor_65d26b_idx'),
        ),
        migrations.AddIndex(
            model_name='receta',
            index=models.Index(fields=['autor', '-fecha_creacion'], name='recetas_rec_autor_i_0f8d3c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('usuario', 'receta')},
        ),
        migrations.AlterUniqueTogether(
            name='favorito',
            unique_together={('usuario', 'receta')},
        ),
        migrations.AlterUniqueTogether(
            name='recetaingrediente',
            unique_together={('receta', 'ingrediente')},
        ),
    ]
